# Generated by Django 2.2.4 on 2019-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.TextField(max_length=3)),
                ('target_currency', models.TextField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
